export type Video = {
  id: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  videoUrl: string;
  embedUrl?: string;
  source?: "LOCAL" | "YOUTUBE";
  channelId: string;
  views: string;
  uploadedAt: string;
  duration: string;
  category: string;
  likes: string;
  likesCount?: number;
  likedByMe?: boolean;
  viewsCount?: number;
  visibility?: string;
  status?: string;
};
