export type Video = {
  id: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  previewUrl?: string;
  videoUrl: string;
  embedUrl?: string;
  source?: "LOCAL" | "YOUTUBE";
  channelId: string;
  views: string;
  uploadedAt: string;
  duration: string;
  category: string;
  tags: string[];
  likes: string;
  likesCount?: number;
  commentCount?: number;
  likedByMe?: boolean;
  viewsCount?: number;
  visibility?: string;
  status?: string;
  availableQualities?: number[];
  subtitles?: Array<{ id: string; language: string; label: string; src: string }>;
};
